---
site_name: Scrapli Community
site_description: Easily add support for 'non-core' platforms to scrapli
site_author: Carl Montanari
site_url: https://scrapli.github.io/

repo_name: scrapli/scrapli_community
repo_url: https://github.com/scrapli/scrapli_community
edit_uri: ''

theme:
    name: material
    palette:
      primary: 'black'
      accent: 'teal'
    icon:
      repo: fontawesome/brands/github-alt

nav:
  - Scrapli Community: index.md
  - User Guide:
      - Quick Start Guide: user_guide/quickstart.md
      - Project Details: user_guide/project_details.md
      - Versioning: user_guide/versioning.md
      - Installation: user_guide/installation.md
      - Basic Usage: user_guide/basic_usage.md
  - API Reference: reference/
  - Changelog: changelog.md
  - More Scrapli:
    - Scrapli: more_scrapli/scrapli.md
    - Scrapli Netconf: more_scrapli/scrapli_netconf.md
    - Scrapli Cfg: more_scrapli/scrapli_cfg.md
    - Scrapli Replay: more_scrapli/scrapli_replay.md
    - Nornir Scrapli: more_scrapli/nornir_scrapli.md
    - Scrapli SCP: more_scrapli/scrapli_scp.md
  - Other:
    - Contributing: about/contributing.md
    - Code of Conduct: about/code_of_conduct.md

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - codehilite
    - extra
    - mdx_gh_links:
        user: scrapli
        repo: scrapli_community
    - pymdownx.superfences
    - pymdownx.highlight:
        use_pygments: True
        linenums: True

extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: 'https://github.com/carlmontanari/'
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/carlrmontanari'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/in/carl-montanari-47888931/'
        - icon: fontawesome/solid/globe
          link: 'https://montanari.io'

plugins:
    - search
    - gen-files:
        scripts:
        - docs/generate.py
    - mkdocstrings:
        handlers:
          python:
            paths: [ scrapli_community ]
            options:
              show_signature_annotations: true
    - section-index
    - literate-nav

watch:
    - scrapli_community